#!/usr/bin/env python3
from __future__ import annotations

import importlib.util
from pathlib import Path

import pandas as pd

spec = importlib.util.spec_from_file_location("ifrb_common", Path(__file__).with_name("00_common.py"))
C = importlib.util.module_from_spec(spec)
spec.loader.exec_module(C)


def values():
    m = C.load_tta_metrics()
    src = m[m["Method"].eq("Step2.9 source-only DG ensemble")].iloc[0]
    best = m[m["Method"].eq(C.best_tta_method())].iloc[0]
    return {
        "auc": float(src["AUC"]),
        "cin3_fn_src": int(src["CIN3+ FN"]),
        "cin3_fn_tta": int(best["CIN3+ FN"]),
        "cin3_sens_src": float(src["CIN3+ sensitivity"]),
        "cin3_sens_tta": float(best["CIN3+ sensitivity"]),
        "gap": float(src["Centre gap"]),
    }


def e50_coe() -> None:
    text = (
        "The chain-of-evidence component is positioned in this Route B manuscript as a transparency aid rather than as a validated explanation endpoint. "
        "The CoE text is generated by a lightweight decoder conditioned on latent belief states and trained with template-derived supervision rather than free-form clinical notes. "
        "Although the stepwise outputs are clinically readable, formal faithfulness evaluation, such as expert assessment, evidence-removal perturbation, or contrastive explanation validation, has not been conducted in the present study. "
        "The CoE module should therefore be interpreted as a transparency aid and a direction for future evaluation, rather than a clinically validated explanation system. "
        "This distinction is important because the present evidence is centred on locked multicentre prediction, target-adaptation boundaries, and failure-centre analysis. "
        "Readable intermediate text may help researchers inspect how clinical priors, colposcopy-derived evidence, OCT-derived evidence, and posterior risk estimates are arranged inside the analysis framework, but readability alone does not establish causal faithfulness or clinical correctness. "
        "Accordingly, CoE examples should be presented as supplementary interpretability artefacts. They may support qualitative inspection of the reliability-aware fusion process, but they should not be used as independent diagnostic evidence or as proof that the model attends to the same cues as expert clinicians. "
        "Future work should evaluate CoE outputs with clinician scoring, perturbation-based evidence removal, and contrastive checks across matched cases before stronger explanation claims are made. "
        "In the current manuscript, this conservative framing keeps the interpretation aligned with the empirical scope of the Route B package: a benchmark and reliability-boundary analysis under centre shift."
    )
    C.write_text(C.OUT / "paper_sections" / "sec_interpretability_coe.txt", text + "\n")
    prompt = "# E50 CoE Repositioning Prompt\n\nUse the CoE module as a transparency aid. Do not treat readable generated steps as proof of clinical faithfulness. Connect the section to reliability-boundary analysis and future expert validation.\n"
    C.write_text(C.OUT / "paper_prompts" / "E50_CoE_Repositioning_Prompt.md", prompt)
    C.append_manifest("E50", "CoE Repositioning", "COMPLETED", ["paper_sections/sec_interpretability_coe.txt", "paper_prompts/E50_CoE_Repositioning_Prompt.md"])


def writing_outputs() -> None:
    v = values()
    abstract = (
        f"Multicentre medical AI systems often degrade when deployed across hospitals with different case mix and acquisition characteristics. "
        f"We analysed a locked n=1897 five-centre leave-one-centre-out benchmark for cervical lesion screening to characterise reliability-aware multimodal fusion under centre shift. "
        f"The primary endpoint was CIN2+ and the safety endpoint was CIN3+. "
        f"The strongest source-only HyDRA-DG safety ensemble reached pooled CIN2+ AUC {v['auc']:.3f}, while CIN3+ sensitivity remained {v['cin3_sens_src']:.3f} with {v['cin3_fn_src']} false negatives. "
        f"Transparent score-level target adaptation reduced CIN3+ false negatives to {v['cin3_fn_tta']} and increased CIN3+ sensitivity to {v['cin3_sens_tta']:.3f}, but it did not materially improve pooled AUC or reduce the centre-level gap. "
        f"The hardest held-out centre concentrated residual safety failures and retained low ranking performance, showing that operating-point adaptation and case-level ranking robustness are separable evaluation problems. "
        f"These results support a Route B framing: the study provides a systematic benchmark and reliability-boundary analysis for multimodal fusion under multicentre shift, while leaving image-level adaptation and formal explanation validation for future work."
    )
    C.write_text(C.OUT / "paper_sections" / "W01_Abstract_Draft.txt", abstract + "\n")
    intro = (
        "Multicentre deployment is one of the central reliability challenges for medical AI. Models trained on one hospital or a small group of hospitals may encounter different imaging devices, acquisition protocols, referral patterns, cytology distributions, HPV profiles, and pathology prevalence at another site. In cervical lesion screening, this problem is amplified by the need to combine heterogeneous information: clinical priors, colposcopy images, OCT information, and text-derived or template-derived semantic cues. A model that appears acceptable in pooled analysis can still fail at the centre level, especially when the most clinically important endpoint is high-grade disease safety rather than average ranking alone.\n\n"
        "Existing multimodal fusion studies often emphasise aggregate performance, while providing limited evidence about where cross-centre reliability breaks down. The gap is not only methodological but also evidential. Reviewers and clinical readers need to know whether improvement comes from better ranking, threshold movement, calibration, centre-specific case mix, or selective gains in easier hospitals. Without protocol separation, transductive adaptation can also be confused with source-only generalisation. This motivates an analysis framework that treats domain shift, safety, calibration, and hard-centre failure as first-class experimental objects.\n\n"
        "In this Route B study, HyDRA-DG is used as a benchmark and analysis framework for reliability-aware multimodal fusion under a locked five-centre LOCO protocol. The source-only track evaluates inductive cross-centre generalisation. A separate transductive track evaluates score-level target adaptation using unlabelled target-centre distributions without target labels. The analysis deliberately avoids presenting adaptation as deployment-ready source-only performance. Instead, it asks how far score-level adaptation can move operating points, reduce false negatives, and whether it can repair ranking failure when a centre is genuinely hard.\n\n"
        "The contributions are fourfold. First, we provide a locked n=1897 multicentre benchmark with explicit endpoint and protocol audits. Second, we compare clinical, unimodal, fusion, DG, and score-level TTA variants with comparability flags. Third, we quantify centre shift, centre separability, safety trade-offs, calibration, decision curves, and screening efficiency. Fourth, we analyse the hardest held-out centre to show that pooled AUC recovery and worst-centre safety are separable. The resulting manuscript is positioned as a diagnostic benchmark and reliability-boundary analysis rather than a finished deployment system."
    )
    C.write_text(C.OUT / "paper_sections" / "W02_Introduction_Draft.txt", intro + "\n")
    method = """3.1 Overview of HyDRA Reliability-Aware Fusion
Describe the patient-level multimodal fusion framework and its Route B benchmark positioning.

3.2 Heterogeneous Multimodal Feature Encoding
Summarise clinical, colposcopy, OCT, and semantic/template-derived inputs, with explicit file provenance.

3.3 Adaptive Reliability-Weighted Fusion
Describe reliability weighting as an analysis component, avoiding stronger claims than the available evidence supports.

3.4 Risk-Guided Iterative Evidence Accumulation
Present iterative evidence accumulation as an internal modelling structure and benchmark artefact.

3.5 Guideline-Aligned Clinical Decision Support
Define endpoints, thresholds, and safety-oriented operating points under locked LOCO evaluation.

3.6 Domain-Generalisation Ensemble Strategy
Describe inner-centre validation, DG ensemble selection, and source-only evaluation.

3.7 Evaluation Protocol
Separate inductive source-only LOCO from transductive score-level TTA and list leakage controls.
"""
    C.write_text(C.OUT / "paper_sections" / "W03_Method_Framework.txt", method)
    exp = """4. Experimental Setup
4.1 Dataset and Clinical Endpoints
4.2 Evaluation Protocol
4.3 Baselines and Implementation Details

5. Results and Analysis
5.1 Domain Shift Characterisation
5.2 Fusion Strategy Benchmark
5.3 Score-Level Target Adaptation Analysis
5.4 Failure Centre Analysis
5.5 Clinical Evaluation
5.6 Interpretability and Chain-of-Evidence
"""
    C.write_text(C.OUT / "paper_sections" / "W04_Experiment_Structure.txt", exp)
    discussion = (
        "The main finding is that threshold-level improvement and ranking-level reliability are distinct. Score-level target adaptation moved operating points and reduced CIN3+ false negatives under the selected safety threshold, but it did not improve the hardest-centre AUC or reduce the centre gap. This means that a lower false-negative count can be achieved by screening more patients positive, while the model still lacks the ordering quality needed to separate high-risk and low-risk cases within the hardest centre. For multicentre fusion systems, this distinction is crucial: pooled AUC recovery does not guarantee worst-centre safety, and calibration or threshold adjustment does not necessarily solve representation or case-mix mismatch.\n\n"
        "The study has several limitations. The target adaptation evaluated here is prediction-level TTA only, because an auditable image-level checkpoint for adaptive BN or TENT-style feature adaptation was not available in this final package. CoE outputs are template-supervised transparency aids and do not yet have expert faithfulness validation. The hardest-centre findings require confirmation in additional multicentre cohorts. The CIN3+ sensitivity target was approached by the best score-level TTA candidate but not fully reached. Some historical baseline rows are included with comparability flags and should not be overused for superiority claims.\n\n"
        "Future work should rebuild the runner around saved fold-specific image encoders, source validation features, and target unlabelled feature logs. This would allow true feature-level DG/TTA, including adaptive normalisation, entropy minimisation, feature alignment, and worst-centre objective selection. Clinical translation also requires prospective validation, expert review of explanations, and threshold policies agreed before deployment. The current Route B package provides the evidence needed to make those next steps more disciplined: it documents the boundary of what score-level adaptation can repair and where stronger image-level modelling is required."
    )
    C.write_text(C.OUT / "paper_sections" / "W05_Discussion_Framework.txt", discussion + "\n")
    C.append_manifest("W01-W05", "Writing outputs", "COMPLETED", ["paper_sections/W01_Abstract_Draft.txt", "paper_sections/W02_Introduction_Draft.txt", "paper_sections/W03_Method_Framework.txt", "paper_sections/W04_Experiment_Structure.txt", "paper_sections/W05_Discussion_Framework.txt"])


def main() -> None:
    C.ensure_dirs()
    e50_coe()
    writing_outputs()


if __name__ == "__main__":
    main()
